#!/bin/bash

LIBNAME=libvbs
LOCAL_LIBPATH=${LOCAL_LIBPATH:-~/.local/lib}
LIBPATH=${LIBPATH:-/usr/local/lib}
IP_ADDR=$(ip a show dev eth0| grep -e '\<inet\>' | awk '{print $2}' | awk -F / '{print $1}')

if [ -f $LOCAL_LIBPATH/$LIBNAME ]
then
    . $LOCAL_LIBPATH/$LIBNAME
elif [ -f $LIBPATH/$LIBNAME ]
then
    . $LIBPATH/$LIBNAME
else
    quit "$LIBNAME not found in either $LOCAL_LIBPATH or $LIBPATH"
fi

/home/openbts/openbtsconfig SIP.Local.IP $IP_ADDR

echo starting openbts
BTS_PID=$(run_openbts)
echo $BTS_PID

check_openbts
