#!/bin/bash
unset TMUX

if tmux has-session -t sipserver >/dev/null 2>&1 
then
    echo "Error: sipserver session alreay exists"
    exit 1
elif tmux -q has-session
then
    tmux new-session -d -s sipserver -n console
else
    tmux new-session -d -s sipserver -n console
fi

tmux split-window -t sipserver:0
tmux new-window -t sipserver:1 -n misc

tmux send-keys -t sipserver:1 'run_sip' C-m
sleep 5
tmux send-keys -t sipserver:0.0 'tail -f /var/log/OpenBTS.log' C-m

tmux select-window -t sipserver:1
tmux attach-session -d -t sipserver
exit 0
